name: GitHub CI

on: [push]

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, ubuntu-24.04-arm, windows-11-arm, macos-13]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: python -m pip install meson ninja
      - name: Prepare build
        run: meson setup build
      - name: Run build
        run: meson compile -C build
